apiVersion: v1
kind: Namespace
metadata:
  name: a-feladat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-feladat-wordpress-deployment
  namespace: a-feladat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-feladat-wordpress
  template:
    metadata:
      labels:
        app: a-feladat-wordpress
    spec: 
      containers:
      - image: wordpress:6.7-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "a-feladat-mysql-service"
        - name: WORDPRESS_DB_USER
          value: "wordpress"
        - name: WORDPRESS_DB_PASSWORD
          value: "wordpress-szuper-erűs"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        ports:
        - containerPort: 80
          name: wordpress
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-feladat-mysql-pod
  namespace: a-feladat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-feladat-mysql
  template:
    metadata:
      labels:
        app: a-feladat-mysql
    spec: 
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "wordpress"
        - name: MYSQL_USER
          value: "wordpress"
        - name: MYSQL_PASSWORD
          value: "wordpress-szuper-erűs"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: '1'
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: 1
